### PR TITLE
color customization

### PR DESCRIPTION
**Pull request by ac615223s5**

### CODE REVIEW

**Comment by rocksdanister** [comment]
I see that you have `colorConfig2` in the listener fn but not in the property, is that intentional?

**Comment by ac615223s5** [comment]
no

**Comment by rocksdanister** [comment]
So its a text input for custom color? I would remove that since Lively colorpicker already has text input.

Looking at the code, for the old random color behaviour both colors need to be black right? instead I would put a checkbox below the `color right` something like "Random Color".

In the future I will support hiding/enabling other controls based on checkbox which should make it clearer.

**Comment by ac615223s5** [comment]
The text input allows multiple color ranges. like [[weight,color,color],[weight,color,color],...].

**Comment by ac615223s5** [comment]
I guess default case for when both are black can be removed, and if the user selects hsv(0,1,1) to hsv(1,1,1) then the behaviour will be what it was before

**Comment by rocksdanister** [comment]
>The text input allows multiple color ranges. like [[weight,color,color],[weight,color,color],...].

That's cool but I would remove it in the final product (in `LivelyProperties.json` but keep the js code) since the average user would be confused and end up creating support tickets.

> if the user selects hsv(0,1,1) to hsv(1,1,1) then the behaviour will be what it was before

No, what I meant is create a checkbox for `Random Color` after color right.

**Pull request merged**
